package com.carenexus.common.error;

public enum ErrorCode {
    SUCCESS("SUCCESS"),
    BAD_REQUEST("BAD_REQUEST"),
    UNAUTHORIZED("UNAUTHORIZED"),
    FORBIDDEN("FORBIDDEN"),
    NOT_FOUND("NOT_FOUND"),
    CONFLICT("CONFLICT"),
    AUTH_INVALID_CREDENTIALS("AUTH_INVALID_CREDENTIALS"),
    AUTH_TOKEN_MISSING("AUTH_TOKEN_MISSING"),
    AUTH_TOKEN_INVALID("AUTH_TOKEN_INVALID"),
    AUTH_TOKEN_EXPIRED("AUTH_TOKEN_EXPIRED"),
    AUTH_TOKEN_REVOKED("AUTH_TOKEN_REVOKED"),
    AUTH_ACCOUNT_DISABLED("AUTH_ACCOUNT_DISABLED"),
    AUTH_UNAUTHORIZED("AUTH_UNAUTHORIZED"),
    AUTH_FORBIDDEN("AUTH_FORBIDDEN"),
    VALIDATION_ERROR("VALIDATION_ERROR"),
    BUSINESS_ERROR("BUSINESS_ERROR"),
    SYSTEM_ERROR("SYSTEM_ERROR");

    private final String code;

    ErrorCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }
}
